2017-12-07 21:02:19.771 +03:00 [Information] Request starting HTTP/1.1 GET http://127.0.0.1:5000/test/get  
2017-12-07 21:02:19.939 +03:00 [Information] Executing action method "Service.Tester.Controllers.TestController.Get (Service.Tester)" with arguments (null) - ModelState is Valid
2017-12-07 21:02:19.949 +03:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2017-12-07 21:02:19.968 +03:00 [Information] Executed action "Service.Tester.Controllers.TestController.Get (Service.Tester)" in 35.5531ms
2017-12-07 21:02:19.971 +03:00 [Information] Request finished in 208.3471ms 200 text/plain; charset=utf-8
2017-12-07 21:02:28.118 +03:00 [Information] Request starting HTTP/1.1 GET http://127.0.0.1:5000/compile/run  
2017-12-07 21:02:28.123 +03:00 [Information] Request finished in 5.3ms 404 
2017-12-07 21:03:00.346 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run  0
2017-12-07 21:03:00.391 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 9.0549ms
2017-12-07 21:03:00.392 +03:00 [Error] Connection id ""0HL9TJIKASF01"", Request id ""0HL9TJIKASF01:00000003"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Unable to resolve service for type 'Service.Compilation.Interfaces.ICompiler' while attempting to activate 'Service.Tester.Controllers.CompileController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-12-07 21:03:00.454 +03:00 [Information] Request finished in 107.7066ms 500 
2017-12-07 21:06:25.213 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run  0
2017-12-07 21:06:25.404 +03:00 [Information] Executing HttpStatusCodeResult, setting HTTP status code 415
2017-12-07 21:06:25.411 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 31.7165ms
2017-12-07 21:06:25.416 +03:00 [Information] Request finished in 209.3ms 415 
2017-12-07 21:06:42.169 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run  0
2017-12-07 21:06:42.171 +03:00 [Information] Executing HttpStatusCodeResult, setting HTTP status code 415
2017-12-07 21:06:42.172 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 1.72ms
2017-12-07 21:06:42.173 +03:00 [Information] Request finished in 3.8934ms 415 
2017-12-07 21:07:41.334 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 0
2017-12-07 21:07:41.346 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:09:54.504 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 125
2017-12-07 21:09:54.661 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:09:54.677 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 62.3548ms
2017-12-07 21:09:54.680 +03:00 [Error] Connection id ""0HL9TJMRRQCFU"", Request id ""0HL9TJMRRQCFU:00000001"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Service.Compilation.Roslyn.RoslynCompiler.Compile(String source, String exeName, List`1 assemblyLocations) in D:\Dev\Service.Tester\Service.Tester\Service.Compilation\Roslyn\RoslynCompiler.cs:line 44
   at Service.Tester.Controllers.CompileController.Run(String sourceCode) in D:\Dev\Service.Tester\Service.Tester\Service.Tester\Controllers\CompileController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-12-07 21:09:54.729 +03:00 [Information] Request finished in 230.369ms 500 
2017-12-07 21:10:28.890 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 125
2017-12-07 21:10:29.117 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:10:45.099 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 16040.6111ms
2017-12-07 21:10:45.102 +03:00 [Error] Connection id ""0HL9TJN63J5F5"", Request id ""0HL9TJN63J5F5:00000001"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Service.Compilation.Roslyn.RoslynCompiler.Compile(String source, String exeName, List`1 assemblyLocations) in D:\Dev\Service.Tester\Service.Tester\Service.Compilation\Roslyn\RoslynCompiler.cs:line 44
   at Service.Tester.Controllers.CompileController.Run(String sourceCode) in D:\Dev\Service.Tester\Service.Tester\Service.Tester\Controllers\CompileController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-12-07 21:10:45.160 +03:00 [Information] Request finished in 16276.4692ms 500 
2017-12-07 21:11:07.575 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run text/plain 124
2017-12-07 21:11:07.582 +03:00 [Information] Executing HttpStatusCodeResult, setting HTTP status code 415
2017-12-07 21:11:07.584 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 7.6739ms
2017-12-07 21:11:07.586 +03:00 [Information] Request finished in 10.8528ms 415 
2017-12-07 21:12:10.699 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 143
2017-12-07 21:12:10.702 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:12:24.138 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 13438.0348ms
2017-12-07 21:12:24.141 +03:00 [Error] Connection id ""0HL9TJN63J5F5"", Request id ""0HL9TJN63J5F5:00000003"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Service.Compilation.Roslyn.RoslynCompiler.Compile(String source, String exeName, List`1 assemblyLocations) in D:\Dev\Service.Tester\Service.Tester\Service.Compilation\Roslyn\RoslynCompiler.cs:line 44
   at Service.Tester.Controllers.CompileController.Run(String sourceCode) in D:\Dev\Service.Tester\Service.Tester\Service.Tester\Controllers\CompileController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-12-07 21:12:24.167 +03:00 [Information] Request finished in 13468.4371ms 500 
2017-12-07 21:12:59.806 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 99
2017-12-07 21:12:59.808 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:13:25.835 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 26027.3639ms
2017-12-07 21:13:25.838 +03:00 [Error] Connection id ""0HL9TJN63J5F5"", Request id ""0HL9TJN63J5F5:00000004"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Service.Compilation.Roslyn.RoslynCompiler.Compile(String source, String exeName, List`1 assemblyLocations) in D:\Dev\Service.Tester\Service.Tester\Service.Compilation\Roslyn\RoslynCompiler.cs:line 44
   at Service.Tester.Controllers.CompileController.Run(String sourceCode) in D:\Dev\Service.Tester\Service.Tester\Service.Tester\Controllers\CompileController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-12-07 21:13:25.874 +03:00 [Information] Request finished in 26068.3144ms 500 
2017-12-07 21:13:29.217 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 103
2017-12-07 21:13:29.219 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:14:21.468 +03:00 [Information] Executed action "Service.Tester.Controllers.CompileController.Run (Service.Tester)" in 52249.7506ms
2017-12-07 21:14:21.472 +03:00 [Error] Connection id ""0HL9TJN63J5F5"", Request id ""0HL9TJN63J5F5:00000005"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Service.Compilation.Roslyn.RoslynCompiler.Compile(String source, String exeName, List`1 assemblyLocations) in D:\Dev\Service.Tester\Service.Tester\Service.Compilation\Roslyn\RoslynCompiler.cs:line 44
   at Service.Tester.Controllers.CompileController.Run(String sourceCode) in D:\Dev\Service.Tester\Service.Tester\Service.Tester\Controllers\CompileController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-12-07 21:14:21.507 +03:00 [Information] Request finished in 52289.6536ms 500 
2017-12-07 21:14:24.728 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 227
2017-12-07 21:14:24.730 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Invalid
2017-12-07 21:16:39.874 +03:00 [Information] Request starting HTTP/1.1 POST http://127.0.0.1:5000/compile/run application/json 227
2017-12-07 21:16:40.064 +03:00 [Information] Executing action method "Service.Tester.Controllers.CompileController.Run (Service.Tester)" with arguments ([""]) - ModelState is Valid
